"""update user table, create token type and user token verification table

Revision ID: 4698e447285d
Revises: 7f120e9b778f
Create Date: 2025-12-16 09:00:43.075251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4698e447285d'
down_revision: Union[str, Sequence[str], None] = '7f120e9b778f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expires_in_minutes', sa.Integer(), nullable=False),
    sa.Column('single_use', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('token_type_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_type_id'], ['token_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_verification_tokens_token_type_id'), 'user_verification_tokens', ['token_type_id'], unique=False)
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    bind = op.get_bind()

    bind.execute(sa.text("""
                         INSERT INTO token_types (name, expires_in_minutes, single_use)
                         VALUES ('verify_email', 60, TRUE),('reset_password', 60, TRUE)
                         """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_index(op.f('ix_user_verification_tokens_token_type_id'), table_name='user_verification_tokens')
    op.drop_table('user_verification_tokens')
    op.drop_table('token_types')
    # ### end Alembic commands ###
